# Interactive build configuration → config/build.conf (UUID-based).
# shellcheck shell=bash

lfs_build_conf_path() {
  echo "${ROOT}/config/build.conf"
}

lfs_uuid_for_partition() {
  local dev=$1
  local uuid fstype

  if [[ ! -b "${dev}" ]]; then
    echo "Not a block device: ${dev}" >&2
    return 1
  fi
  uuid="$(blkid -s UUID -o value "${dev}" 2>/dev/null || true)"
  if [[ -z "${uuid}" ]]; then
    echo "No UUID on ${dev} (create a filesystem first)" >&2
    return 1
  fi
  fstype="$(blkid -s TYPE -o value "${dev}" 2>/dev/null || true)"
  echo "${uuid} ${fstype}"
}

lfs_prompt_value() {
  local __var=$1 __default=$2 __label=$3 __input
  if [[ -n "${LFS_YES:-}" ]]; then
    printf -v "${__var}" '%s' "${__default}"
    echo "  ${__label}: ${__default} (default)"
    return 0
  fi
  read -erp "${__label} [${__default}]: " __input
  printf -v "${__var}" '%s' "${__input:-${__default}}"
}

lfs_prompt_password() {
  local __var=$1 __label=$2 __default=$3
  local pass1 pass2
  if [[ -n "${LFS_YES:-}" ]]; then
    printf -v "${__var}" '%s' "${__default}"
    echo "  ${__label}: (default — change in production!)"
    return 0
  fi
  while true; do
    read -rsp "${__label}: " pass1
    echo
    read -rsp "Confirm ${__label}: " pass2
    echo
    if [[ -z "${pass1}" ]]; then
      echo "Password cannot be empty." >&2
      continue
    fi
    if [[ "${pass1}" != "${pass2}" ]]; then
      echo "Passwords do not match, try again." >&2
      continue
    fi
    printf -v "${__var}" '%s' "${pass1}"
    break
  done
}

lfs_write_build_conf() {
  local path
  path="$(lfs_build_conf_path)"
  mkdir -p "$(dirname "${path}")"
  {
    echo "# Generated by lfs-build.sh configure — $(date -Iseconds)"
    echo "# UUIDs are stable across device renames; re-run configure after repartitioning."
    echo "# Contains passwords — keep private (chmod 600)."
    echo
    printf 'export LFS=%q\n' "${LFS}"
    printf 'export ROOT_UUID=%q\n' "${ROOT_UUID}"
    printf 'export ROOT_FSTYPE=%q\n' "${ROOT_FSTYPE}"
    printf 'export ESP_UUID=%q\n' "${ESP_UUID}"
    printf 'export ESP_MOUNT=%q\n' "${ESP_MOUNT}"
    printf 'export SWAP_UUID=%q\n' "${SWAP_UUID}"
    printf 'export GRUB_INSTALL_MODE=%q\n' "${GRUB_INSTALL_MODE}"
    printf 'export GRUB_BOOTLOADER_ID=%q\n' "${GRUB_BOOTLOADER_ID}"
    printf 'export USE_INITRAMFS=%q\n' "${USE_INITRAMFS}"
    printf 'export KERNEL_RELEASE=%q\n' "${KERNEL_RELEASE}"
    printf 'export LINUX_VERSION=%q\n' "${LINUX_VERSION}"
    printf 'export OS_NAME=%q\n' "${OS_NAME}"
    printf 'export OS_VERSION=%q\n' "${OS_VERSION}"
    printf 'export OS_CODENAME=%q\n' "${OS_CODENAME}"
    printf 'export HOSTNAME=%q\n' "${HOSTNAME}"
    printf 'export DOMAIN=%q\n' "${DOMAIN}"
    printf 'export SYSTEM_ISSUE=%q\n' "${SYSTEM_ISSUE}"
    printf 'export LANG=%q\n' "${LANG}"
    printf 'export LC_COLLATE=%q\n' "${LC_COLLATE}"
    printf 'export LC_TIME=%q\n' "${LC_TIME}"
    printf 'export TIMEZONE=%q\n' "${TIMEZONE}"
    printf 'export HWCLOCK_UTC=%q\n' "${HWCLOCK_UTC}"
    printf 'export KEYMAP=%q\n' "${KEYMAP}"
    printf 'export CONSOLE_FONT=%q\n' "${CONSOLE_FONT}"
    printf 'export GROFF_PAPER_SIZE=%q\n' "${GROFF_PAPER_SIZE}"
    printf 'export SYSTEM_USER=%q\n' "${SYSTEM_USER}"
    printf 'export ROOT_PASSWORD=%q\n' "${ROOT_PASSWORD}"
    printf 'export USER_PASSWORD=%q\n' "${USER_PASSWORD}"
    printf 'export NETWORK_MODE=%q\n' "${NETWORK_MODE}"
    printf 'export STATIC_IP=%q\n' "${STATIC_IP}"
    printf 'export GATEWAY=%q\n' "${GATEWAY}"
    printf 'export DNS=%q\n' "${DNS}"
  } >"${path}"
  chmod 600 "${path}"
  echo "Wrote ${path}"
}

lfs_show_build_config() {
  echo "Current build configuration:"
  echo "  LFS mount:       ${LFS}"
  echo "  Root UUID:       ${ROOT_UUID:-<unset>} (${ROOT_FSTYPE:-?})"
  echo "  ESP UUID:        ${ESP_UUID:-<none>}"
  echo "  Swap UUID:       ${SWAP_UUID:-<none>}"
  echo "  OS:              ${OS_NAME:-?} ${OS_VERSION:-?} (${OS_CODENAME:-?})"
  echo "  Hostname:        ${HOSTNAME:-<unset>}"
  echo "  Domain:          ${DOMAIN:-<unset>}"
  echo "  Locale LANG:     ${LANG:-<unset>}"
  echo "  Timezone:        ${TIMEZONE:-<unset>}"
  echo "  Keymap:          ${KEYMAP:-<unset>}"
  echo "  Groff paper:     ${GROFF_PAPER_SIZE:-<unset>}"
  echo "  System user:     ${SYSTEM_USER:-<unset>}"
  echo "  Root password:   ${ROOT_PASSWORD:+<set>}${ROOT_PASSWORD:-<unset>}"
  echo "  User password:   ${USER_PASSWORD:+<set>}${USER_PASSWORD:-<unset>}"
  echo "  Network:         ${NETWORK_MODE:-<unset>}"
  echo "  GRUB mode:       ${GRUB_INSTALL_MODE}"
  echo "  Initramfs:       ${USE_INITRAMFS}"
  echo "  Kernel rel:      ${KERNEL_RELEASE}"
}

lfs_interactive_configure() {
  local force=${1:-0}
  local conf ans
  local root_dev esp_dev swap_dev root_uuid root_fstype esp_uuid swap_uuid
  local line

  conf="$(lfs_build_conf_path)"
  if [[ "${force}" -eq 0 && -f "${conf}" && -n "${ROOT_UUID:-}" ]]; then
    if [[ -z "${LFS_YES:-}" && -z "${LFS_RECONFIGURE:-}" ]]; then
      lfs_show_build_config
      read -erp "Use this configuration? [Y/n]: " ans
      if [[ "${ans,,}" != n && "${ans,,}" != no ]]; then
        return 0
      fi
    elif [[ -z "${LFS_RECONFIGURE:-}" ]]; then
      return 0
    fi
  fi

  echo "=== Aryalinux LFS build configuration ==="
  echo "Press Enter for [bracketed] defaults. LFS_YES=1 accepts all defaults."
  echo

  echo "--- Disk layout (paths used once to read UUIDs) ---"
  lfs_prompt_value LFS "${LFS:-${LFS_DEFAULT}}" "LFS mount point"
  lfs_prompt_value root_dev "${ROOT_PARTITION_DEFAULT}" "Root partition"
  line="$(lfs_uuid_for_partition "${root_dev}")" || return 1
  read -r root_uuid root_fstype <<<"${line}"

  lfs_prompt_value esp_dev "${ESP_PARTITION_DEFAULT}" "EFI System Partition (- for none)"
  esp_uuid=""
  if [[ -n "${esp_dev}" && "${esp_dev}" != "-" ]]; then
    line="$(lfs_uuid_for_partition "${esp_dev}")" || return 1
    read -r esp_uuid _ <<<"${line}"
  fi

  lfs_prompt_value swap_dev "${SWAP_PARTITION_DEFAULT}" "Swap partition (- for none)"
  swap_uuid=""
  if [[ -n "${swap_dev}" && "${swap_dev}" != "-" ]]; then
    line="$(lfs_uuid_for_partition "${swap_dev}")" || return 1
    read -r swap_uuid _ <<<"${line}"
  fi

  echo
  echo "--- System identity (LFS ch.9 / ch.11) ---"
  lfs_prompt_value OS_NAME "${OS_NAME:-${OS_NAME_DEFAULT}}" "OS name"
  lfs_prompt_value OS_VERSION "${OS_VERSION:-${OS_VERSION_DEFAULT}}" "OS version"
  lfs_prompt_value OS_CODENAME "${OS_CODENAME:-${OS_CODENAME_DEFAULT}}" "OS codename"
  SYSTEM_ISSUE="${OS_NAME} ${OS_VERSION} (${OS_CODENAME})"
  lfs_prompt_value HOSTNAME "${HOSTNAME:-${HOSTNAME_DEFAULT}}" "Hostname (short name)"
  lfs_prompt_value DOMAIN "${DOMAIN:-${DOMAIN_DEFAULT}}" "Domain name (e.g. localdomain)"
  lfs_prompt_value SYSTEM_ISSUE "${SYSTEM_ISSUE}" "Login banner (/etc/issue)"

  echo
  echo "--- Locale and time (LFS ch.9) ---"
  lfs_prompt_value LANG "${LANG:-${LANG_DEFAULT}}" "System locale (LANG in /etc/locale.conf)"
  lfs_prompt_value LC_COLLATE "${LC_COLLATE:-${LC_COLLATE_DEFAULT}}" "LC_COLLATE override (- for none)"
  lfs_prompt_value LC_TIME "${LC_TIME:-${LC_TIME_DEFAULT}}" "LC_TIME override (- for none)"
  lfs_prompt_value TIMEZONE "${TIMEZONE:-${TIMEZONE_DEFAULT}}" "Timezone (timedatectl)"
  lfs_prompt_value HWCLOCK_UTC "${HWCLOCK_UTC:-${HWCLOCK_UTC_DEFAULT}}" "Hardware clock is UTC (1=yes, 0=local)"

  echo
  echo "--- Console (LFS ch.9 vconsole.conf) ---"
  lfs_prompt_value KEYMAP "${KEYMAP:-${KEYMAP_DEFAULT}}" "Keyboard layout (localectl keymap)"
  lfs_prompt_value CONSOLE_FONT "${CONSOLE_FONT:-${CONSOLE_FONT_DEFAULT}}" "Console font (FONT=)"

  echo
  echo "--- Groff paper size (LFS ch.8) ---"
  lfs_prompt_value GROFF_PAPER_SIZE "${GROFF_PAPER_SIZE:-${GROFF_PAPER_SIZE_DEFAULT}}" "Groff PAGE (A4 or letter)"

  echo
  echo "--- Users (LFS ch.11 — applied after shadow in chroot) ---"
  lfs_prompt_value SYSTEM_USER "${SYSTEM_USER:-${SYSTEM_USER_DEFAULT}}" "Normal user login name"
  lfs_prompt_password ROOT_PASSWORD "Root password" "${ROOT_PASSWORD:-${ROOT_PASSWORD_DEFAULT}}"
  lfs_prompt_password USER_PASSWORD "Password for ${SYSTEM_USER}" "${USER_PASSWORD:-${USER_PASSWORD_DEFAULT}}"

  echo
  echo "--- Network (LFS ch.9) ---"
  lfs_prompt_value NETWORK_MODE "${NETWORK_MODE:-${NETWORK_MODE_DEFAULT}}" "Network mode (dhcp|static|none)"
  NETWORK_MODE="${NETWORK_MODE,,}"
  if [[ "${NETWORK_MODE}" == static ]]; then
    lfs_prompt_value STATIC_IP "${STATIC_IP:-${STATIC_IP_DEFAULT}}" "Static IP (CIDR, e.g. 192.168.1.10/24)"
    lfs_prompt_value GATEWAY "${GATEWAY:-${GATEWAY_DEFAULT}}" "Default gateway"
    lfs_prompt_value DNS "${DNS:-${DNS_DEFAULT}}" "DNS server(s), space-separated"
  elif [[ "${NETWORK_MODE}" == none ]]; then
    STATIC_IP="${STATIC_IP_DEFAULT}"
    GATEWAY="${GATEWAY_DEFAULT}"
    DNS="${DNS_DEFAULT}"
  else
    NETWORK_MODE=dhcp
    STATIC_IP="${STATIC_IP_DEFAULT}"
    GATEWAY="${GATEWAY_DEFAULT}"
    DNS="${DNS_DEFAULT}"
  fi

  echo
  echo "--- Boot loader ---"
  lfs_prompt_value GRUB_INSTALL_MODE "${GRUB_INSTALL_MODE:-removable}" "GRUB install (removable|efibootmgr)"
  lfs_prompt_value USE_INITRAMFS "${USE_INITRAMFS:-1}" "Build initramfs (1|0)"

  [[ "${LC_COLLATE}" == "-" ]] && LC_COLLATE=""
  [[ "${LC_TIME}" == "-" ]] && LC_TIME=""

  if [[ -z "${esp_uuid}" && "${GRUB_INSTALL_MODE}" == efibootmgr ]]; then
    echo "EFI partition is required for efibootmgr GRUB install." >&2
    return 1
  fi

  export ROOT_UUID="${root_uuid}" ROOT_FSTYPE="${root_fstype}"
  export ESP_UUID="${esp_uuid}" SWAP_UUID="${swap_uuid}"

  lfs_write_build_conf
  echo
  lfs_show_build_config
}

lfs_ensure_build_config() {
  if [[ -z "${ROOT_UUID:-}" ]]; then
    lfs_interactive_configure 0
  fi
  if [[ -z "${ROOT_UUID:-}" ]]; then
    echo "Build configuration incomplete. Run: sudo ./lfs-build.sh configure" >&2
    exit 1
  fi
}
